name: Project Pipeline Test

on:
  push:
    paths:
      - 'data/**'
      - 'project/**'
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

          # Install python
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
            python-version: 3.11.5

      - name: Run file
        run: |
          chmod +x ./project/test.sh
          ./project/test.sh
